version: "1"
rules:
  - base: master
    upstream: collin80:master
    mergeMethod: hardreset
  - base: dev
    upstream: master
    assignees:
      - Tichael
    reviewers:
      - Tichael
    conflictReviewers:
      - Tichael
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
